#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.8
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require File.expand_path("../lexer", __FILE__)
  require File.expand_path("../nodes", __FILE__)
  require 'pp'

module Riml
  class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 154)
  # This code will be put as-is in the parser class

  # parses tokens or code into output nodes
  def parse(object, show_tokens=false)
    @tokens = if tokens?(object)
      object
    elsif code?(object)
      Riml::Lexer.new.tokenize(object)
    end
    pp(@tokens) if show_tokens
    do_parse
  end

  def next_token
    @tokens.shift
  end

  private
  # is an array of arrays and first five inner arrays are all doubles
  def tokens?(object)
    Array === object and object[0..4].all? {|e| e.respond_to?(:size) and e.size == 2}
  end

  def code?(object)
    String === object
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    77,    39,    40,    82,   104,    14,    14,    82,    72,    72,
    72,    14,    79,    95,    78,    94,    31,    32,    39,    40,
    37,    38,    33,    34,    35,    36,    30,    29,    75,    15,
    15,    71,    87,    31,    32,    15,    72,    95,    43,   105,
    42,    39,    40,    37,    38,    93,    39,    40,    37,    38,
    33,    34,    35,    36,    30,    29,    31,    32,    25,    31,
    32,    31,    32,    26,    24,    31,    32,    14,    16,    17,
    18,    19,    20,    21,    22,    23,    46,    50,    47,    39,
    40,    37,    38,    33,    34,    35,    36,    25,    44,    13,
    82,    15,    26,    24,    31,    32,    14,    16,    17,    18,
    19,    20,    21,    22,    23,    84,    45,    85,    39,    40,
    37,    38,    84,   101,    72,   103,    25,    82,    13,    69,
    15,    26,    24,    31,    32,    14,    16,    17,    18,    19,
    20,    21,    22,    23,    82,    82,   107,    72,    27,    82,
    73,   nil,   nil,   nil,   nil,    39,    40,    13,   nil,    15,
    39,    40,    37,    38,    33,    34,    35,    36,    30,    29,
    31,    32,    25,   nil,   nil,    31,    32,    26,    24,   nil,
   nil,   nil,    16,    17,    18,    19,    20,    21,    22,    23,
   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,   nil,    26,
    24,   nil,   nil,    13,    16,    17,    18,    19,    20,    21,
    22,    23,   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,
   nil,    26,    24,   nil,   nil,    13,    16,    17,    18,    19,
    20,    21,    22,    23,   nil,   nil,   nil,   nil,    25,   nil,
   nil,   nil,   nil,    26,    24,   nil,   nil,    13,    16,    17,
    18,    19,    20,    21,    22,    23,   nil,   nil,   nil,   nil,
    25,   nil,   nil,   nil,   nil,    26,    24,   nil,   nil,    13,
    16,    17,    18,    19,    20,    21,    22,    23,   nil,   nil,
   nil,   nil,    25,   nil,   nil,   nil,   nil,    26,    24,   nil,
   nil,    13,    16,    17,    18,    19,    20,    21,    22,    23,
   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,   nil,    26,
    24,   nil,   nil,    13,    16,    17,    18,    19,    20,    21,
    22,    23,   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,
   nil,    26,    24,   nil,   nil,    13,    16,    17,    18,    19,
    20,    21,    22,    23,   nil,   nil,   nil,   nil,    25,   nil,
   nil,    82,   nil,    26,    24,   nil,   nil,    13,    16,    17,
    18,    19,    20,    21,    22,    23,    39,    40,    37,    38,
    33,    34,    35,    36,    30,    29,   nil,   nil,    25,    13,
   nil,    31,    32,    26,    24,   nil,   nil,   nil,    16,    17,
    18,    19,    20,    21,    22,    23,   nil,   nil,   nil,   nil,
    25,   nil,   nil,   nil,   nil,    26,    24,   nil,   nil,    13,
    16,    17,    18,    19,    20,    21,    22,    23,   nil,   nil,
   nil,   nil,    25,   nil,   nil,   nil,   nil,    26,    24,   nil,
   nil,    13,    16,    17,    18,    19,    20,    21,    22,    23,
   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,   nil,    26,
    24,   nil,   nil,    13,    16,    17,    18,    19,    20,    21,
    22,    23,   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,
   nil,    26,    24,   nil,   nil,    13,    16,    17,    18,    19,
    20,    21,    22,    23,   nil,   nil,   nil,   nil,    25,   nil,
   nil,   nil,   nil,    26,    24,   nil,   nil,    13,    16,    17,
    18,    19,    20,    21,    22,    23,   nil,   nil,   nil,   nil,
    25,   nil,   nil,   nil,   nil,    26,    24,   nil,   nil,    13,
    16,    17,    18,    19,    20,    21,    22,    23,   nil,   nil,
   nil,   nil,    25,   nil,   nil,   nil,   nil,    26,    24,   nil,
   nil,    13,    16,    17,    18,    19,    20,    21,    22,    23,
   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,   nil,    26,
    24,   nil,   nil,    13,    16,    17,    18,    19,    20,    21,
    22,    23,   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,
   nil,    26,    24,   nil,   nil,    13,    16,    17,    18,    19,
    20,    21,    22,    23,   nil,   nil,   nil,   nil,    25,   nil,
   nil,   nil,   nil,    26,    24,   nil,   nil,    13,    16,    17,
    18,    19,    20,    21,    22,    23,   nil,   nil,   nil,   nil,
    25,   nil,   nil,   nil,   nil,    26,    24,   nil,   nil,    13,
    16,    17,    18,    19,    20,    21,    22,    23,   nil,   nil,
   nil,   nil,    25,   nil,   nil,   nil,   nil,    26,    24,   nil,
   nil,    13,    16,    17,    18,    19,    20,    21,    22,    23,
   nil,   nil,   nil,   nil,    25,   nil,   nil,   nil,   nil,    26,
    24,   nil,   nil,    13,    16,    17,    18,    19,    20,    21,
    22,    23,    39,    40,    37,    38,    33,    34,    35,    36,
    30,    29,   nil,   nil,   nil,    13,   nil,    31,    32,    39,
    40,    37,    38,    33,    34,    35,    36,    30,    29,    39,
    40,    37,    38,   nil,    31,    32,   nil,   nil,   nil,   nil,
    39,    40,    37,    38,    31,    32,    39,    40,    37,    38,
    33,    34,    35,    36,    30,    31,    32,   nil,   nil,   nil,
   nil,    31,    32,    39,    40,    37,    38,    33,    34,    35,
    36,    30,    29,   nil,   nil,   nil,   nil,   nil,    31,    32,
    39,    40,    37,    38,    33,    34,    35,    36,    30,    29,
   nil,   nil,   nil,   nil,   nil,    31,    32,    39,    40,    37,
    38,    33,    34,    35,    36,    30,    29,   nil,   nil,   nil,
   nil,   nil,    31,    32,    39,    40,    37,    38,    33,    34,
    35,    36,    30,    29,   nil,   nil,   nil,   nil,   nil,    31,
    32,    39,    40,    37,    38,    33,    34,    35,    36,    30,
    29,   nil,   nil,   nil,   nil,   nil,    31,    32,    39,    40,
    37,    38,    33,    34,    35,    36,    30,    29,   nil,   nil,
   nil,   nil,   nil,    31,    32,    39,    40,    37,    38,    33,
    34,    35,    36,    30,    29,   nil,   nil,   nil,   nil,   nil,
    31,    32,    39,    40,    37,    38,    33,    34,    35,    36,
    30,    29,   nil,   nil,   nil,    64,   nil,    31,    32 ]

racc_action_check = [
    49,    60,    60,    74,    96,   109,     2,    76,    49,    46,
    73,    96,    65,    83,    65,    83,    60,    60,    49,    49,
    49,    49,    49,    49,    49,    49,    49,    49,    48,   109,
     2,    46,    73,    49,    49,    96,    48,    98,    21,    98,
    21,    58,    58,    58,    58,    82,    48,    48,    48,    48,
    48,    48,    48,    48,    48,    48,    58,    58,   107,    63,
    63,    48,    48,   107,   107,    62,    62,   107,   107,   107,
   107,   107,   107,   107,   107,   107,    24,    27,    24,    53,
    53,    53,    53,    53,    53,    53,    53,    85,    22,   107,
    86,   107,    85,    85,    53,    53,    85,    85,    85,    85,
    85,    85,    85,    85,    85,    87,    23,    72,    56,    56,
    56,    56,    71,    93,    94,    95,     0,    70,    85,    45,
    85,     0,     0,    56,    56,     0,     0,     0,     0,     0,
     0,     0,     0,     0,   102,    89,   104,   105,     1,   108,
    47,   nil,   nil,   nil,   nil,    61,    61,     0,   nil,     0,
    89,    89,    89,    89,    89,    89,    89,    89,    89,    89,
    61,    61,    13,   nil,   nil,    89,    89,    13,    13,   nil,
   nil,   nil,    13,    13,    13,    13,    13,    13,    13,    13,
   nil,   nil,   nil,   nil,    79,   nil,   nil,   nil,   nil,    79,
    79,   nil,   nil,    13,    79,    79,    79,    79,    79,    79,
    79,    79,   nil,   nil,   nil,   nil,    77,   nil,   nil,   nil,
   nil,    77,    77,   nil,   nil,    79,    77,    77,    77,    77,
    77,    77,    77,    77,   nil,   nil,   nil,   nil,    25,   nil,
   nil,   nil,   nil,    25,    25,   nil,   nil,    77,    25,    25,
    25,    25,    25,    25,    25,    25,   nil,   nil,   nil,   nil,
    26,   nil,   nil,   nil,   nil,    26,    26,   nil,   nil,    25,
    26,    26,    26,    26,    26,    26,    26,    26,   nil,   nil,
   nil,   nil,    75,   nil,   nil,   nil,   nil,    75,    75,   nil,
   nil,    26,    75,    75,    75,    75,    75,    75,    75,    75,
   nil,   nil,   nil,   nil,    28,   nil,   nil,   nil,   nil,    28,
    28,   nil,   nil,    75,    28,    28,    28,    28,    28,    28,
    28,    28,   nil,   nil,   nil,   nil,    29,   nil,   nil,   nil,
   nil,    29,    29,   nil,   nil,    28,    29,    29,    29,    29,
    29,    29,    29,    29,   nil,   nil,   nil,   nil,    30,   nil,
   nil,    91,   nil,    30,    30,   nil,   nil,    29,    30,    30,
    30,    30,    30,    30,    30,    30,    91,    91,    91,    91,
    91,    91,    91,    91,    91,    91,   nil,   nil,    32,    30,
   nil,    91,    91,    32,    32,   nil,   nil,   nil,    32,    32,
    32,    32,    32,    32,    32,    32,   nil,   nil,   nil,   nil,
    33,   nil,   nil,   nil,   nil,    33,    33,   nil,   nil,    32,
    33,    33,    33,    33,    33,    33,    33,    33,   nil,   nil,
   nil,   nil,    34,   nil,   nil,   nil,   nil,    34,    34,   nil,
   nil,    33,    34,    34,    34,    34,    34,    34,    34,    34,
   nil,   nil,   nil,   nil,    35,   nil,   nil,   nil,   nil,    35,
    35,   nil,   nil,    34,    35,    35,    35,    35,    35,    35,
    35,    35,   nil,   nil,   nil,   nil,    37,   nil,   nil,   nil,
   nil,    37,    37,   nil,   nil,    35,    37,    37,    37,    37,
    37,    37,    37,    37,   nil,   nil,   nil,   nil,    38,   nil,
   nil,   nil,   nil,    38,    38,   nil,   nil,    37,    38,    38,
    38,    38,    38,    38,    38,    38,   nil,   nil,   nil,   nil,
    39,   nil,   nil,   nil,   nil,    39,    39,   nil,   nil,    38,
    39,    39,    39,    39,    39,    39,    39,    39,   nil,   nil,
   nil,   nil,    40,   nil,   nil,   nil,   nil,    40,    40,   nil,
   nil,    39,    40,    40,    40,    40,    40,    40,    40,    40,
   nil,   nil,   nil,   nil,    69,   nil,   nil,   nil,   nil,    69,
    69,   nil,   nil,    40,    69,    69,    69,    69,    69,    69,
    69,    69,   nil,   nil,   nil,   nil,    42,   nil,   nil,   nil,
   nil,    42,    42,   nil,   nil,    69,    42,    42,    42,    42,
    42,    42,    42,    42,   nil,   nil,   nil,   nil,    43,   nil,
   nil,   nil,   nil,    43,    43,   nil,   nil,    42,    43,    43,
    43,    43,    43,    43,    43,    43,   nil,   nil,   nil,   nil,
    44,   nil,   nil,   nil,   nil,    44,    44,   nil,   nil,    43,
    44,    44,    44,    44,    44,    44,    44,    44,   nil,   nil,
   nil,   nil,    31,   nil,   nil,   nil,   nil,    31,    31,   nil,
   nil,    44,    31,    31,    31,    31,    31,    31,    31,    31,
   nil,   nil,   nil,   nil,    36,   nil,   nil,   nil,   nil,    36,
    36,   nil,   nil,    31,    36,    36,    36,    36,    36,    36,
    36,    36,    54,    54,    54,    54,    54,    54,    54,    54,
    54,    54,   nil,   nil,   nil,    36,   nil,    54,    54,    55,
    55,    55,    55,    55,    55,    55,    55,    55,    55,    57,
    57,    57,    57,   nil,    55,    55,   nil,   nil,   nil,   nil,
    59,    59,    59,    59,    57,    57,    52,    52,    52,    52,
    52,    52,    52,    52,    52,    59,    59,   nil,   nil,   nil,
   nil,    52,    52,    51,    51,    51,    51,    51,    51,    51,
    51,    51,    51,   nil,   nil,   nil,   nil,   nil,    51,    51,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
   nil,   nil,   nil,   nil,   nil,     3,     3,    80,    80,    80,
    80,    80,    80,    80,    80,    80,    80,   nil,   nil,   nil,
   nil,   nil,    80,    80,    92,    92,    92,    92,    92,    92,
    92,    92,    92,    92,   nil,   nil,   nil,   nil,   nil,    92,
    92,    66,    66,    66,    66,    66,    66,    66,    66,    66,
    66,   nil,   nil,   nil,   nil,   nil,    66,    66,    67,    67,
    67,    67,    67,    67,    67,    67,    67,    67,   nil,   nil,
   nil,   nil,   nil,    67,    67,    68,    68,    68,    68,    68,
    68,    68,    68,    68,    68,   nil,   nil,   nil,   nil,   nil,
    68,    68,    41,    41,    41,    41,    41,    41,    41,    41,
    41,    41,   nil,   nil,   nil,    41,   nil,    41,    41 ]

racc_action_pointer = [
   114,   138,    -5,   729,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   160,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,     7,    57,    89,    59,   226,   248,    77,   292,   314,
   336,   630,   366,   388,   410,   432,   652,   454,   476,   498,
   520,   831,   564,   586,   608,    88,    -2,   123,    25,    -3,
   nil,   712,   695,    58,   651,   668,    87,   678,    20,   689,
   -20,   124,    29,    23,   nil,   -20,   780,   797,   814,   542,
   111,    95,    98,    -1,    -3,   270,     1,   204,   nil,   182,
   746,   nil,    34,   -19,   nil,    85,    84,    88,   nil,   129,
   nil,   335,   763,   103,   103,    98,     0,   nil,     5,   nil,
   nil,   nil,   128,   nil,   125,   126,   nil,    56,   133,    -6,
   nil ]

racc_action_default = [
    -1,   -59,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -59,   -16,   -17,   -18,   -19,   -20,   -21,
   -22,   -23,   -40,   -59,   -59,   -59,   -59,   -59,    -5,   -59,
   -59,   -59,   -59,   -59,   -59,   -59,   -59,   -59,   -59,   -59,
   -59,   -59,   -25,   -59,   -59,   -59,   -59,   -59,   -59,   -59,
   111,    -4,   -28,   -29,   -30,   -31,   -32,   -33,   -34,   -35,
   -36,   -37,   -38,   -39,   -15,   -59,   -26,   -41,   -43,   -59,
   -59,   -50,   -59,   -59,   -59,   -59,   -59,   -59,   -24,   -59,
   -42,   -44,   -49,   -59,   -51,   -59,   -59,   -50,   -53,   -59,
   -55,   -59,   -27,   -59,   -59,   -59,   -58,   -46,   -59,   -54,
   -56,   -48,   -59,   -52,   -59,   -59,   -45,   -59,   -59,   -57,
   -47 ]

racc_goto_table = [
    28,     2,    41,    70,    65,    74,    76,     1,   nil,   nil,
   nil,   nil,   nil,   nil,    48,    49,   nil,    51,    52,    53,
    54,    55,    56,    57,    58,    59,    60,    61,    62,    63,
    86,    66,    67,    68,    83,   nil,   nil,   nil,    81,   nil,
   nil,   nil,    88,   nil,    90,   nil,   nil,   nil,   nil,   nil,
    98,   102,   nil,   nil,    97,   nil,   nil,    99,    80,   100,
   nil,   nil,   108,   nil,    89,   nil,    91,   nil,    92,   nil,
   106,   nil,   nil,   nil,   nil,   nil,   110,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    96,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    28,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,    28,   109 ]

racc_goto_check = [
     4,     2,     3,    14,    13,    14,    14,     1,   nil,   nil,
   nil,   nil,   nil,   nil,     3,     3,   nil,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,     3,
    14,     3,     3,     3,    16,   nil,   nil,   nil,    15,   nil,
   nil,   nil,    15,   nil,    15,   nil,   nil,   nil,   nil,   nil,
    16,    14,   nil,   nil,    15,   nil,   nil,    15,     3,    15,
   nil,   nil,    14,   nil,     3,   nil,     3,   nil,     3,   nil,
    15,   nil,   nil,   nil,   nil,   nil,    15,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,     4,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,     4,     2 ]

racc_goto_pointer = [
   nil,     7,     1,   -11,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   -38,   -43,   -32,   -37 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    11,    12,   nil,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 39, :_reduce_1,
  1, 39, :_reduce_2,
  1, 40, :_reduce_3,
  3, 40, :_reduce_4,
  2, 40, :_reduce_5,
  1, 40, :_reduce_6,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  1, 41, :_reduce_none,
  3, 41, :_reduce_15,
  1, 42, :_reduce_none,
  1, 42, :_reduce_none,
  1, 43, :_reduce_18,
  1, 43, :_reduce_19,
  1, 43, :_reduce_20,
  1, 43, :_reduce_21,
  1, 43, :_reduce_22,
  1, 44, :_reduce_23,
  4, 44, :_reduce_24,
  0, 51, :_reduce_25,
  1, 51, :_reduce_26,
  3, 51, :_reduce_27,
  3, 45, :_reduce_28,
  3, 45, :_reduce_29,
  3, 45, :_reduce_30,
  3, 45, :_reduce_31,
  3, 45, :_reduce_32,
  3, 45, :_reduce_33,
  3, 45, :_reduce_34,
  3, 45, :_reduce_35,
  3, 45, :_reduce_36,
  3, 45, :_reduce_37,
  3, 45, :_reduce_38,
  3, 45, :_reduce_39,
  1, 46, :_reduce_40,
  3, 47, :_reduce_41,
  4, 47, :_reduce_42,
  3, 47, :_reduce_43,
  4, 48, :_reduce_44,
  7, 48, :_reduce_45,
  5, 48, :_reduce_46,
  8, 48, :_reduce_47,
  3, 53, :_reduce_none,
  1, 53, :_reduce_none,
  0, 54, :_reduce_50,
  1, 54, :_reduce_51,
  3, 54, :_reduce_52,
  4, 49, :_reduce_53,
  5, 49, :_reduce_54,
  4, 50, :_reduce_55,
  5, 50, :_reduce_56,
  6, 52, :_reduce_57,
  3, 52, :_reduce_58 ]

racc_reduce_n = 59

racc_shift_n = 111

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :THEN => 3,
  :ELSE => 4,
  :ELSIF => 5,
  :END => 6,
  :UNLESS => 7,
  :DEF => 8,
  :INDENT => 9,
  :DEDENT => 10,
  :NEWLINE => 11,
  :NUMBER => 12,
  :STRING => 13,
  :TRUE => 14,
  :FALSE => 15,
  :NIL => 16,
  :IDENTIFIER => 17,
  :CONSTANT => 18,
  :SCOPE_MODIFIER => 19,
  "!" => 20,
  "*" => 21,
  "/" => 22,
  "+" => 23,
  "-" => 24,
  ">" => 25,
  ">=" => 26,
  "<" => 27,
  "<=" => 28,
  "&&" => 29,
  "||" => 30,
  "=" => 31,
  "," => 32,
  "(" => 33,
  ")" => 34,
  ";" => 35,
  "==" => 36,
  "!=" => 37 }

racc_nt_base = 38

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "THEN",
  "ELSE",
  "ELSIF",
  "END",
  "UNLESS",
  "DEF",
  "INDENT",
  "DEDENT",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "SCOPE_MODIFIER",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "\"==\"",
  "\"!=\"",
  "$start",
  "Root",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "Constant",
  "Assign",
  "Def",
  "If",
  "Unless",
  "ArgList",
  "Block",
  "End",
  "ParamList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 28)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 29)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 34)
  def _reduce_3(val, _values, result)
     result = Nodes.new([ val[0] ]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 35)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 36)
  def _reduce_5(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 37)
  def _reduce_6(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

module_eval(<<'.,.,', 'grammar.y', 50)
  def _reduce_15(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 16 omitted

# reduce 17 omitted

module_eval(<<'.,.,', 'grammar.y', 60)
  def _reduce_18(val, _values, result)
     result = NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 61)
  def _reduce_19(val, _values, result)
     result = StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 62)
  def _reduce_20(val, _values, result)
     result = TrueNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 63)
  def _reduce_21(val, _values, result)
     result = FalseNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 64)
  def _reduce_22(val, _values, result)
     result = NilNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 70)
  def _reduce_23(val, _values, result)
     result = CallNode.new(val[0], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 72)
  def _reduce_24(val, _values, result)
     result = CallNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 76)
  def _reduce_25(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 77)
  def _reduce_26(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 78)
  def _reduce_27(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 83)
  def _reduce_28(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 84)
  def _reduce_29(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 85)
  def _reduce_30(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 86)
  def _reduce_31(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 87)
  def _reduce_32(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 88)
  def _reduce_33(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 89)
  def _reduce_34(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 90)
  def _reduce_35(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 91)
  def _reduce_36(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 92)
  def _reduce_37(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 93)
  def _reduce_38(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 94)
  def _reduce_39(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 98)
  def _reduce_40(val, _values, result)
     result = GetConstantNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 103)
  def _reduce_41(val, _values, result)
     result = SetVariableNode.new(nil, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 104)
  def _reduce_42(val, _values, result)
     result = SetVariableNode.new(val[0], val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 105)
  def _reduce_43(val, _values, result)
     result = SetConstantNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 111)
  def _reduce_44(val, _values, result)
     indent = val[2].pop; result = DefNode.new(nil,    val[1], [],     val[2], indent) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 112)
  def _reduce_45(val, _values, result)
     indent = val[5].pop; result = DefNode.new(nil,    val[1], val[3], val[5], indent) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 113)
  def _reduce_46(val, _values, result)
     indent = val[3].pop; result = DefNode.new(val[1], val[2], [],     val[3], indent) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 114)
  def _reduce_47(val, _values, result)
     indent = val[6].pop; result = DefNode.new(val[1], val[2], val[4], val[6], indent) 
    result
  end
.,.,

# reduce 48 omitted

# reduce 49 omitted

module_eval(<<'.,.,', 'grammar.y', 123)
  def _reduce_50(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 124)
  def _reduce_51(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 125)
  def _reduce_52(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 130)
  def _reduce_53(val, _values, result)
     indent = val[2].pop; result = IfNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 131)
  def _reduce_54(val, _values, result)
     result = IfNode.new( val[1], Nodes.new([val[3]]) ) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 135)
  def _reduce_55(val, _values, result)
     indent = val[2].pop; result = UnlessNode.new(val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 136)
  def _reduce_56(val, _values, result)
     result = UnlessNode.new( val[1], Nodes.new([val[3]]) ) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 142)
  def _reduce_57(val, _values, result)
     result = val[2] << ElseNode.new(val[5]) << val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 143)
  def _reduce_58(val, _values, result)
     result = val[2] << val[1] 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Riml
