#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.8
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require File.expand_path("../lexer", __FILE__)
  require File.expand_path("../nodes", __FILE__)
  require 'pp'

module Riml
  class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 140)
  # This code will be put as-is in the parser class

  def parse(code, show_tokens=false)
    @tokens = Riml::Lexer.new.tokenize(code)
    pp(@tokens) if show_tokens
    do_parse
  end

  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    24,    13,    69,    43,    23,    69,    77,    13,    15,    16,
    17,    18,    19,    20,    21,    22,    87,    73,    47,    72,
    13,    44,    76,    45,    68,    14,    24,    79,    42,    12,
    23,    14,    76,    13,    15,    16,    17,    18,    19,    20,
    21,    22,    66,    82,    14,    81,    41,    82,    40,    88,
    24,    37,    38,    69,    23,    12,    86,    14,    15,    16,
    17,    18,    19,    20,    21,    22,    29,    30,    29,    30,
    29,    30,    24,    37,    38,    25,    23,    70,    69,    12,
    15,    16,    17,    18,    19,    20,    21,    22,    29,    30,
   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,    23,   nil,
   nil,    12,    15,    16,    17,    18,    19,    20,    21,    22,
   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,
    23,   nil,   nil,    12,    15,    16,    17,    18,    19,    20,
    21,    22,   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,
   nil,   nil,    23,   nil,   nil,    12,    15,    16,    17,    18,
    19,    20,    21,    22,   nil,   nil,   nil,   nil,   nil,   nil,
    24,   nil,   nil,   nil,    23,   nil,   nil,    12,    15,    16,
    17,    18,    19,    20,    21,    22,   nil,   nil,   nil,   nil,
   nil,   nil,    24,   nil,   nil,   nil,    23,   nil,   nil,    12,
    15,    16,    17,    18,    19,    20,    21,    22,   nil,   nil,
   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,    23,   nil,
   nil,    12,    15,    16,    17,    18,    19,    20,    21,    22,
   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,
    23,   nil,   nil,    12,    15,    16,    17,    18,    19,    20,
    21,    22,   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,
   nil,   nil,    23,   nil,   nil,    12,    15,    16,    17,    18,
    19,    20,    21,    22,   nil,   nil,   nil,   nil,   nil,   nil,
    24,   nil,   nil,   nil,    23,   nil,   nil,    12,    15,    16,
    17,    18,    19,    20,    21,    22,   nil,   nil,   nil,   nil,
   nil,   nil,    24,   nil,   nil,   nil,    23,   nil,   nil,    12,
    15,    16,    17,    18,    19,    20,    21,    22,   nil,   nil,
   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,    23,   nil,
   nil,    12,    15,    16,    17,    18,    19,    20,    21,    22,
   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,
    23,   nil,   nil,    12,    15,    16,    17,    18,    19,    20,
    21,    22,   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,
   nil,   nil,    23,   nil,   nil,    12,    15,    16,    17,    18,
    19,    20,    21,    22,   nil,   nil,   nil,   nil,   nil,   nil,
    24,   nil,   nil,   nil,    23,   nil,   nil,    12,    15,    16,
    17,    18,    19,    20,    21,    22,   nil,   nil,   nil,   nil,
   nil,   nil,    24,   nil,   nil,   nil,    23,   nil,   nil,    12,
    15,    16,    17,    18,    19,    20,    21,    22,   nil,   nil,
   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,    23,   nil,
   nil,    12,    15,    16,    17,    18,    19,    20,    21,    22,
   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,
    23,   nil,   nil,    12,    15,    16,    17,    18,    19,    20,
    21,    22,   nil,   nil,   nil,   nil,   nil,   nil,    24,   nil,
   nil,   nil,    23,   nil,    69,    12,    15,    16,    17,    18,
    19,    20,    21,    22,    37,    38,    35,    36,    31,    32,
    33,    34,    28,    27,   nil,   nil,   nil,    12,   nil,    29,
    30,    37,    38,    35,    36,    31,    32,    33,    34,    28,
   nil,   nil,   nil,   nil,   nil,   nil,    29,    30,    37,    38,
    35,    36,    31,    32,    33,    34,    28,    27,   nil,   nil,
   nil,   nil,   nil,    29,    30,    37,    38,    35,    36,    31,
    32,    33,    34,    28,    27,   nil,   nil,   nil,    61,   nil,
    29,    30,    37,    38,    35,    36,    31,    32,    33,    34,
    28,    27,   nil,   nil,   nil,   nil,   nil,    29,    30,    37,
    38,    35,    36,    31,    32,    33,    34,    28,    27,   nil,
   nil,   nil,   nil,   nil,    29,    30,    37,    38,    35,    36,
    31,    32,    33,    34,    28,    27,   nil,   nil,   nil,   nil,
   nil,    29,    30,    37,    38,    35,    36,    31,    32,    33,
    34,    28,    27,    37,    38,    35,    36,   nil,    29,    30,
    37,    38,    35,    36,    31,    32,    33,    34,    29,    30,
   nil,   nil,   nil,   nil,   nil,    29,    30,    37,    38,    35,
    36,    31,    32,    33,    34,    28,    27,   nil,   nil,   nil,
   nil,   nil,    29,    30,    37,    38,    35,    36,    31,    32,
    33,    34,    28,    27,    37,    38,    35,    36,   nil,    29,
    30,    37,    38,    35,    36,    37,    38,    35,    36,    29,
    30,   nil,   nil,   nil,   nil,   nil,    29,    30,   nil,   nil,
    29,    30,    37,    38,    35,    36,    31,    32,    33,    34,
    28,    27,   nil,   nil,   nil,   nil,   nil,    29,    30,    37,
    38,    35,    36,    31,    32,    33,    34,    28,    27,   nil,
   nil,   nil,   nil,   nil,    29,    30 ]

racc_action_check = [
     0,     2,    44,    22,     0,    70,    69,     0,     0,     0,
     0,     0,     0,     0,     0,     0,    83,    62,    25,    62,
    83,    23,    68,    23,    44,     2,    77,    70,    21,     0,
    77,     0,    79,    77,    77,    77,    77,    77,    77,    77,
    77,    77,    43,    75,    83,    75,    20,    84,    20,    84,
    36,    57,    57,    81,    36,    77,    82,    77,    36,    36,
    36,    36,    36,    36,    36,    36,    57,    57,    59,    59,
    60,    60,    41,    58,    58,     1,    41,    45,    88,    36,
    41,    41,    41,    41,    41,    41,    41,    41,    58,    58,
   nil,   nil,   nil,   nil,    12,   nil,   nil,   nil,    12,   nil,
   nil,    41,    12,    12,    12,    12,    12,    12,    12,    12,
   nil,   nil,   nil,   nil,   nil,   nil,    40,   nil,   nil,   nil,
    40,   nil,   nil,    12,    40,    40,    40,    40,    40,    40,
    40,    40,   nil,   nil,   nil,   nil,   nil,   nil,    66,   nil,
   nil,   nil,    66,   nil,   nil,    40,    66,    66,    66,    66,
    66,    66,    66,    66,   nil,   nil,   nil,   nil,   nil,   nil,
    38,   nil,   nil,   nil,    38,   nil,   nil,    66,    38,    38,
    38,    38,    38,    38,    38,    38,   nil,   nil,   nil,   nil,
   nil,   nil,    73,   nil,   nil,   nil,    73,   nil,   nil,    38,
    73,    73,    73,    73,    73,    73,    73,    73,   nil,   nil,
   nil,   nil,   nil,   nil,    24,   nil,   nil,   nil,    24,   nil,
   nil,    73,    24,    24,    24,    24,    24,    24,    24,    24,
   nil,   nil,   nil,   nil,   nil,   nil,    42,   nil,   nil,   nil,
    42,   nil,   nil,    24,    42,    42,    42,    42,    42,    42,
    42,    42,   nil,   nil,   nil,   nil,   nil,   nil,    26,   nil,
   nil,   nil,    26,   nil,   nil,    42,    26,    26,    26,    26,
    26,    26,    26,    26,   nil,   nil,   nil,   nil,   nil,   nil,
    27,   nil,   nil,   nil,    27,   nil,   nil,    26,    27,    27,
    27,    27,    27,    27,    27,    27,   nil,   nil,   nil,   nil,
   nil,   nil,    28,   nil,   nil,   nil,    28,   nil,   nil,    27,
    28,    28,    28,    28,    28,    28,    28,    28,   nil,   nil,
   nil,   nil,   nil,   nil,    29,   nil,   nil,   nil,    29,   nil,
   nil,    28,    29,    29,    29,    29,    29,    29,    29,    29,
   nil,   nil,   nil,   nil,   nil,   nil,    30,   nil,   nil,   nil,
    30,   nil,   nil,    29,    30,    30,    30,    30,    30,    30,
    30,    30,   nil,   nil,   nil,   nil,   nil,   nil,    31,   nil,
   nil,   nil,    31,   nil,   nil,    30,    31,    31,    31,    31,
    31,    31,    31,    31,   nil,   nil,   nil,   nil,   nil,   nil,
    32,   nil,   nil,   nil,    32,   nil,   nil,    31,    32,    32,
    32,    32,    32,    32,    32,    32,   nil,   nil,   nil,   nil,
   nil,   nil,    33,   nil,   nil,   nil,    33,   nil,   nil,    32,
    33,    33,    33,    33,    33,    33,    33,    33,   nil,   nil,
   nil,   nil,   nil,   nil,    34,   nil,   nil,   nil,    34,   nil,
   nil,    33,    34,    34,    34,    34,    34,    34,    34,    34,
   nil,   nil,   nil,   nil,   nil,   nil,    35,   nil,   nil,   nil,
    35,   nil,   nil,    34,    35,    35,    35,    35,    35,    35,
    35,    35,   nil,   nil,   nil,   nil,   nil,   nil,    37,   nil,
   nil,   nil,    37,   nil,    46,    35,    37,    37,    37,    37,
    37,    37,    37,    37,    46,    46,    46,    46,    46,    46,
    46,    46,    46,    46,   nil,   nil,   nil,    37,   nil,    46,
    46,    49,    49,    49,    49,    49,    49,    49,    49,    49,
   nil,   nil,   nil,   nil,   nil,   nil,    49,    49,    80,    80,
    80,    80,    80,    80,    80,    80,    80,    80,   nil,   nil,
   nil,   nil,   nil,    80,    80,    39,    39,    39,    39,    39,
    39,    39,    39,    39,    39,   nil,   nil,   nil,    39,   nil,
    39,    39,    63,    63,    63,    63,    63,    63,    63,    63,
    63,    63,   nil,   nil,   nil,   nil,   nil,    63,    63,    74,
    74,    74,    74,    74,    74,    74,    74,    74,    74,   nil,
   nil,   nil,   nil,   nil,    74,    74,    48,    48,    48,    48,
    48,    48,    48,    48,    48,    48,   nil,   nil,   nil,   nil,
   nil,    48,    48,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,    53,    53,    53,    53,   nil,     3,     3,
    50,    50,    50,    50,    50,    50,    50,    50,    53,    53,
   nil,   nil,   nil,   nil,   nil,    50,    50,    51,    51,    51,
    51,    51,    51,    51,    51,    51,    51,   nil,   nil,   nil,
   nil,   nil,    51,    51,    52,    52,    52,    52,    52,    52,
    52,    52,    52,    52,    54,    54,    54,    54,   nil,    52,
    52,    55,    55,    55,    55,    56,    56,    56,    56,    54,
    54,   nil,   nil,   nil,   nil,   nil,    55,    55,   nil,   nil,
    56,    56,    64,    64,    64,    64,    64,    64,    64,    64,
    64,    64,   nil,   nil,   nil,   nil,   nil,    64,    64,    65,
    65,    65,    65,    65,    65,    65,    65,    65,    65,   nil,
   nil,   nil,   nil,   nil,    65,    65 ]

racc_action_pointer = [
    -2,    75,    -8,   584,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    92,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    17,    -1,   -12,     6,   202,    18,   246,   268,   290,   312,
   334,   356,   378,   400,   422,   444,    48,   466,   158,   516,
   114,    70,   224,    13,    -7,    62,   465,   nil,   567,   482,
   601,   618,   635,   594,   645,   652,   656,    32,    54,    34,
    36,   nil,   -13,   533,   673,   690,   136,   nil,     7,    -1,
    -4,   nil,   nil,   180,   550,    13,   nil,    24,   nil,    17,
   499,    44,    41,    11,    17,   nil,   nil,   nil,    69,   nil ]

racc_action_default = [
    -1,   -52,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -52,   -15,   -16,   -17,   -18,   -19,   -20,   -21,
   -22,   -39,   -52,   -52,   -52,   -52,    -5,   -52,   -52,   -52,
   -52,   -52,   -52,   -52,   -52,   -52,   -52,   -52,   -52,   -52,
   -24,   -52,   -52,   -52,   -52,   -52,   -52,    90,    -4,   -27,
   -28,   -29,   -30,   -31,   -32,   -33,   -34,   -35,   -36,   -37,
   -38,   -14,   -52,   -25,   -40,   -42,   -52,   -43,   -47,   -52,
   -52,   -50,   -23,   -52,   -41,   -52,   -48,   -52,   -45,   -47,
   -26,   -52,   -52,   -52,   -52,   -44,   -49,   -51,   -52,   -46 ]

racc_goto_table = [
    26,     2,    39,    67,    75,    71,    62,     1,   nil,   nil,
   nil,   nil,   nil,   nil,    46,    84,    48,    49,    50,    51,
    52,    53,    54,    55,    56,    57,    58,    59,    60,    78,
    63,    64,    65,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    85,   nil,   nil,   nil,   nil,   nil,   nil,    89,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    74,   nil,   nil,   nil,
   nil,   nil,   nil,    80,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,    83,   nil,
   nil,    26 ]

racc_goto_check = [
     4,     2,     3,    13,    14,    13,    12,     1,   nil,   nil,
   nil,   nil,   nil,   nil,     3,    14,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,     3,    13,
     3,     3,     3,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
    13,   nil,   nil,   nil,   nil,   nil,   nil,    13,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     3,   nil,   nil,   nil,
   nil,   nil,   nil,     3,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,
   nil,     4 ]

racc_goto_pointer = [
   nil,     7,     1,   -10,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   -34,   -41,   -64 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     5,     6,     7,     8,     9,
    10,    11,   nil,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 37, :_reduce_1,
  1, 37, :_reduce_2,
  1, 38, :_reduce_3,
  3, 38, :_reduce_4,
  2, 38, :_reduce_5,
  1, 38, :_reduce_6,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  1, 39, :_reduce_none,
  3, 39, :_reduce_14,
  1, 40, :_reduce_none,
  1, 40, :_reduce_none,
  1, 41, :_reduce_17,
  1, 41, :_reduce_18,
  1, 41, :_reduce_19,
  1, 41, :_reduce_20,
  1, 41, :_reduce_21,
  1, 42, :_reduce_22,
  4, 42, :_reduce_23,
  0, 48, :_reduce_24,
  1, 48, :_reduce_25,
  3, 48, :_reduce_26,
  3, 43, :_reduce_27,
  3, 43, :_reduce_28,
  3, 43, :_reduce_29,
  3, 43, :_reduce_30,
  3, 43, :_reduce_31,
  3, 43, :_reduce_32,
  3, 43, :_reduce_33,
  3, 43, :_reduce_34,
  3, 43, :_reduce_35,
  3, 43, :_reduce_36,
  3, 43, :_reduce_37,
  3, 43, :_reduce_38,
  1, 44, :_reduce_39,
  3, 45, :_reduce_40,
  4, 45, :_reduce_41,
  3, 45, :_reduce_42,
  3, 46, :_reduce_43,
  6, 46, :_reduce_44,
  4, 46, :_reduce_45,
  7, 46, :_reduce_46,
  0, 50, :_reduce_47,
  1, 50, :_reduce_48,
  3, 50, :_reduce_49,
  3, 47, :_reduce_50,
  4, 49, :_reduce_51 ]

racc_reduce_n = 52

racc_shift_n = 90

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :ELSE => 3,
  :ELSIF => 4,
  :END => 5,
  :DEF => 6,
  :INDENT => 7,
  :DEDENT => 8,
  :NEWLINE => 9,
  :NUMBER => 10,
  :STRING => 11,
  :TRUE => 12,
  :FALSE => 13,
  :NIL => 14,
  :IDENTIFIER => 15,
  :CONSTANT => 16,
  :SCOPE_MODIFIER => 17,
  "!" => 18,
  "*" => 19,
  "/" => 20,
  "+" => 21,
  "-" => 22,
  ">" => 23,
  ">=" => 24,
  "<" => 25,
  "<=" => 26,
  "&&" => 27,
  "||" => 28,
  "=" => 29,
  "," => 30,
  "(" => 31,
  ")" => 32,
  ";" => 33,
  "==" => 34,
  "!=" => 35 }

racc_nt_base = 36

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "ELSE",
  "ELSIF",
  "END",
  "DEF",
  "INDENT",
  "DEDENT",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "SCOPE_MODIFIER",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\"(\"",
  "\")\"",
  "\";\"",
  "\"==\"",
  "\"!=\"",
  "$start",
  "Root",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "Constant",
  "Assign",
  "Def",
  "If",
  "ArgList",
  "Block",
  "ParamList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 28)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 29)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 34)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 35)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 36)
  def _reduce_5(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 37)
  def _reduce_6(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

module_eval(<<'.,.,', 'grammar.y', 49)
  def _reduce_14(val, _values, result)
     result = val[1] 
    result
  end
.,.,

# reduce 15 omitted

# reduce 16 omitted

module_eval(<<'.,.,', 'grammar.y', 59)
  def _reduce_17(val, _values, result)
     result = NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 60)
  def _reduce_18(val, _values, result)
     result = StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 61)
  def _reduce_19(val, _values, result)
     result = TrueNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 62)
  def _reduce_20(val, _values, result)
     result = FalseNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 63)
  def _reduce_21(val, _values, result)
     result = NilNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 69)
  def _reduce_22(val, _values, result)
     result = CallNode.new(val[0], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 71)
  def _reduce_23(val, _values, result)
     result = CallNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 75)
  def _reduce_24(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 76)
  def _reduce_25(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 77)
  def _reduce_26(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 82)
  def _reduce_27(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 83)
  def _reduce_28(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 84)
  def _reduce_29(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 85)
  def _reduce_30(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 86)
  def _reduce_31(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 87)
  def _reduce_32(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 88)
  def _reduce_33(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 89)
  def _reduce_34(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 90)
  def _reduce_35(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 91)
  def _reduce_36(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 92)
  def _reduce_37(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 93)
  def _reduce_38(val, _values, result)
     result = CallNode.new(val[0], val[1], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 97)
  def _reduce_39(val, _values, result)
     result = GetConstantNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 102)
  def _reduce_40(val, _values, result)
     result = SetVariableNode.new(nil, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 103)
  def _reduce_41(val, _values, result)
     result = SetVariableNode.new(val[0], val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 104)
  def _reduce_42(val, _values, result)
     result = SetConstantNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 110)
  def _reduce_43(val, _values, result)
     indent = val[2].pop; result = DefNode.new(nil,    val[1], [],     val[2], indent) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 111)
  def _reduce_44(val, _values, result)
     indent = val[5].pop; result = DefNode.new(nil,    val[1], val[3], val[5], indent) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 112)
  def _reduce_45(val, _values, result)
     indent = val[3].pop; result = DefNode.new(val[1], val[2], [],     val[3], indent) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 113)
  def _reduce_46(val, _values, result)
     indent = val[6].pop; result = DefNode.new(val[1], val[2], val[4], val[6], indent) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 117)
  def _reduce_47(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 118)
  def _reduce_48(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 119)
  def _reduce_49(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 124)
  def _reduce_50(val, _values, result)
     indent = val[2].pop; result = IfNode.new(val[1], val[2], indent) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 129)
  def _reduce_51(val, _values, result)
     result = val[2] << val[1].to_i 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

  end   # class Parser
  end   # module Riml
